### ISSUE TITLE
Please tell how to use flag into our ImageView

### ISSUE THREAD

**Issue by cnfuzedRk62** [ahmedAlmasri/DialCountries#1]
i am getting Flag String in the console, but i am not able to set that string on imageView.
I am pasting my code here. 
please suggest how to find the bundle so that imageView can pick the image associating with that string.
Thanks.

 func didSelected(with country: Country) {
    self.flag_ImgView.image = UIImage(named: country.flag)
    self.countryName_Lbl.text = country.name
 }

**Comment by ahmedAlmasri** [comment]
@cnfuzedRk62 we use flag as emoji for lite storage and size 

you can use this extension to convert flags to `UIImage`

```Swift
extension String {
    func toImage() -> UIImage? {
        let size = CGSize(width: 24, height: 24)
        UIGraphicsBeginImageContextWithOptions(size, false, 0)
        UIColor.white.set()
        let rect = CGRect(origin: .zero, size: size)
        UIRectFill(CGRect(origin: .zero, size: size))
        self.draw(in: rect, withAttributes: [.font: UIFont.systemFont(ofSize: 24)])
        let image = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()
        return image
    }
```

Using
```Swift
self.flag_ImgView.image = UIImage(named: country.flag.toImage())
```

**Comment by cnfuzedRk62** [comment]
Thank you so much for your response.

**Comment by ahmedAlmasri** [comment]
@cnfuzedRk62 You are welcome, I will close this issue

**Comment by cnfuzedRk62** [comment]
Sure
